### ISSUE TITLE
Make Parallel in FVCOM

### ISSUE THREAD

**Issue by dharmaraharja96** [pwcazenave/fvcom-toolbox#12]
Hi!

I have an issue to make a parallel setup for FVCOM. When I'm running it with 8 processors on one pc, it is running quickly.
then when I was combined in with 2 pc, with 16 total of processors. the running time is getting lower and also when using 24 processors when using 3 pc. For the set up I used 1 server and 3 clients.  have anyone have solutions on this case? thanks

**Comment by riquitorres** [comment]
Hi
I would assume the pc to pc communications are a bottle neck in your setup. Without something like infiniband as interconectors fvcom will not scale up. For efficient parallel setup you need an HPC rather than a pc grid setup (if that is what your using).


________________________________

**Comment by dharmaraharja96** [comment]
thanks for your response, for my setup parallel I'm using  this link:
https://www.youtube.com/watch?v=gvR1eQyxS9I (for the communication parallel I'm using LAN)
and for the setup in fvcom I'm using the example tutor, how about that? Do you have an assumption for my setup? thanks

**Comment by swaldman3** [comment]
Hi dharmaraharja,

I haven't watched all of the video, but i'm guessing that the two computers are connected to each other using standard gigabit ethernet (or maybe even 100mbps, depending on the network cards). While some software will work just fine on this sort of home-built cluster, FVCOM usually won't. FVCOM requires a lot of communication between subdomains, and hence the network connections can easily be a bottleneck.
HPCssystems that are designed for things like FVCOM use higher performance network links, eg things like Infiniband, Omnilink, etc

Sorry for the bad news!

**Comment by dharmaraharja96** [comment]
Hi Simon

thanks for your information, I'm also trying to setup fvcom parallel on my campus. in my campus using gigabit switch with LAN cable (cat 5e) and the transfer rate data is 1000mbps, but I have the same problem, communication parallel setup not optimum.
Do we have to use the above 1000 mbps also?  and my specific problem is the network?

**Comment by riquitorres** [comment]
Infiniband transfer rate is 200Gbps. I don't know at what value the transfer rate becomes a bottle neck with FVCOM but from your tests it is clear that they are a problem at 1Gbps. There is very little you can do to overcome that limitation other than use multicore computers that don't rely on cpu to cpu transfer.


________________________________

**Comment by swaldman3** [comment]
I can't promise that the network is the problem, but it is very likely. Gigabit ethernet (the 1000mbps that you mention) is generally not good enough for FVCOM. I'm not sure whether the bandwidth or the latency is the problem.

As Ricardo mentioned, infiniband (often used for HPC networks) goes up to 200 times faster, and it also has much lower latency. Unfortunately this is probably not a problem you can solve cheaply. If you have some money to spend, then best to talk to an HPC expert.

**Comment by dharmaraharja96** [comment]
thank you so much Ricardo and Simon for the information
your information really gives me a lot of information

**Comment by swaldman3** [comment]
@riquitorres do you have the ability to close this "issue"? Don't think I can.
